// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnbbxekpwg5OLmDkyhQKFBMhEU-mcwKM8',
    appId: '1:1098703054802:web:203db4204d1c7b21538a0b',
    messagingSenderId: '1098703054802',
    projectId: 'smart-market-71fb8',
    authDomain: 'smart-market-71fb8.firebaseapp.com',
    storageBucket: 'smart-market-71fb8.firebasestorage.app',
    measurementId: 'G-6N4Z4Q3P1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9BoIAKqOiaZY8SwkHubVfoaS3G_d9oNg',
    appId: '1:1098703054802:android:679cc6b9362f2ae9538a0b',
    messagingSenderId: '1098703054802',
    projectId: 'smart-market-71fb8',
    storageBucket: 'smart-market-71fb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt92L3NuD6ow7L_NvjSwqNBqHIGsV1XH0',
    appId: '1:1098703054802:ios:8eef09ca597d79cc538a0b',
    messagingSenderId: '1098703054802',
    projectId: 'smart-market-71fb8',
    storageBucket: 'smart-market-71fb8.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt92L3NuD6ow7L_NvjSwqNBqHIGsV1XH0',
    appId: '1:1098703054802:ios:8eef09ca597d79cc538a0b',
    messagingSenderId: '1098703054802',
    projectId: 'smart-market-71fb8',
    storageBucket: 'smart-market-71fb8.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnbbxekpwg5OLmDkyhQKFBMhEU-mcwKM8',
    appId: '1:1098703054802:web:f7653b7f3b6674bb538a0b',
    messagingSenderId: '1098703054802',
    projectId: 'smart-market-71fb8',
    authDomain: 'smart-market-71fb8.firebaseapp.com',
    storageBucket: 'smart-market-71fb8.firebasestorage.app',
    measurementId: 'G-V3W82ELPWJ',
  );
}
